export const App = {
  HTTP: 'App.HTPP',
  AI: 'App.AI',
}

export const Blocklist = {
  ALL: 'Blocklist.ALL',
  BLOCK_CONTACT: 'Blocklist.BLOCK_CONTACT',
  IS_BLOCKED: 'Blocklist.IS_BLOCKED',
  UNBLOCK_CONTACT: 'Blocklist.UNBLOCK_CONTACT',
}

export const Cart = {
  ADD: 'Cart.ADD',
  CLEAR: 'Cart.CLEAR',
  GET: 'Cart.GET',
  GET_THUMB_FROM_CART: 'Cart.GET_THUMB_FROM_CART',
  REMOVE: 'Cart.REMOVE',
  SUBMIT: 'Cart.SUBMIT',
  UPDATE: 'Cart.UPDATE',
}

export const Catalog = {
  ADD_PRODUCT_IMAGE: 'Catalog.ADD_PRODUCT_IMAGE',
  CHANGE_PRODUCT_IMAGE: 'Catalog.CHANGE_PRODUCT_IMAGE',
  CREATE_COLLECTION: 'Catalog.CREATE_COLLECTION',
  CREATE_PRODUCT: 'Catalog.CREATE_PRODUCT',
  DELETE_COLLECTION: 'Catalog.DELETE_COLLECTION',
  DELETE_PRODUCT: 'Catalog.DELETE_PRODUCT',
  EDIT_COLLECTION: 'Catalog.EDIT_COLLECTION',
  EDIT_PRODUCT: 'Catalog.EDIT_PRODUCT',
  GET_COLLECTIONS: 'Catalog.GET_COLLECTIONS',
  GET_MY_CATALOG: 'Catalog.GET_MY_CATALOG',
  GET_PRODUCT_BY_ID: 'Catalog.GET_PRODUCT_BY_ID',
  GET_PRODUCTS: 'Catalog.GET_PRODUCTS',
  REMOVE_PRODUCT_IMAGE: 'Catalog.REMOVE_PRODUCT_IMAGE',
  SET_PRODUCT_VISIBILITY: 'Catalog.SET_PRODUCT_VISIBILITY',
  UPDAGE_CART_ENABLED: 'Catalog.UPDAGE_CART_ENABLED',
}

export const Community = {
  ADD_SUB_GROUPS: 'Community.ADD_SUB_GROUPS',
}

export const Chat = {
  ARCHIVE: 'Chat.ARCHIVE',
  CAN_MARK_PLAYED: 'Chat.CAN_MARK_PLAYED',
  CAN_MUTE: 'Chat.CAN_MUTE',
  CAN_REPLY: 'Chat.CAN_REPLY',
  CLEAR: 'Chat.CLEAR',
  CLOSE_CHAT: 'Chat.CLOSE_CHAT',
  DELETE: 'Chat.DELETE',
  DELETE_MESSAGE: 'Chat.DELETE_MESSAGE',
  DOWNLOAD_MEDIA: 'Chat.DOWNLOAD_MEDIA', // ++ ADDED
  FIND: 'Chat.FIND',
  FORWARD_MESSAGE: 'Chat.FORWARD_MESSAGE',
  GET: 'Chat.GET',
  GET_ACTIVE_CHAT: 'Chat.GET_ACTIVE_CHAT',
  GET_LAST_SEEN: 'Chat.GET_LAST_SEEN',
  GET_MESSAGE_ACK: 'Chat.GET_MESSAGE_ACK',
  GET_MESSAGES: 'Chat.GET_MESSAGES',
  GET_NOTES: 'Chat.GET_NOTES',
  GET_PLATFORM_MESSAGE: 'Chat.GET_PLATFORM_MESSAGE',
  MARK_IS_COMPOSING: 'Chat.MARK_IS_COMPOSING',
  MARK_IS_PAUSED: 'Chat.MARK_IS_PAUSED',
  MARK_IS_READ: 'Chat.MARK_IS_READ',
  MARK_IS_RECORDING: 'Chat.MARK_IS_RECORDING',
  MARK_IS_UNREAD: 'Chat.MARK_IS_UNREAD',
  MARK_PLAYED: 'Chat.MARK_PLAYED',
  MUTE: 'Chat.MUTE',
  OPEN_CHAT_AT: 'Chat.OPEN_CHAT_AT',
  OPEN_CHAT_BOTTOM: 'Chat.OPEN_CHAT_BOTTOM',
  OPEN_CHAT_FROM_UNREAD: 'Chat.OPEN_CHAT_FROM_UNREAD',
  PIN_MSG: 'Chat.PIN_MSG',
  LIST: 'Chat.LIST',
  SET_CHAT_LIST: 'Chat.SET_CHAT_LIST',
  SET_INPUT_TEXT: 'Chat.SET_INPUT_TEXT',
  SET_NOTES: 'Chat.SET_NOTES',
}

export const Contact = {
  GET: 'Contact.GET',
  GET_BUSINESS_PROFILE: 'Contact.GET_BUSINESS_PROFILE',
  GET_COMMON_GROUPS: 'Contact.GET_COMMON_GROUPS',
  GET_PROFILE_PICTURE_URL: 'Contact.GET_PROFILE_PICTURE_URL',
  GET_STATUS: 'Contact.GET_STATUS',
  LIST: 'Contact.LIST',
  LIST_CONTACT_BY_COUNTRY: 'Contact.LIST_CONTACT_BY_COUNTRY',
  IS_EXIST: 'Contact.IS_EXIST',
  REMOVE: 'Contact.REMOVE',
}

export const Conn = {
  GEN_LINK_DEVICE_CODE_FOR_PHONE_NUMBER:
    'Conn.GEN_LINK_DEVICE_CODE_FOR_PHONE_NUMBER',
  GET_AUTH_CODE: 'Conn.GET_AUTH_CODE',
  GET_PROFILE: 'Conn.GET_PROFILE',
  GET_MY_USER_ID: 'Conn.GET_MY_USER_ID',
}

export const Group = {
  ADD_PARTICIPANTS: 'Group.ADD_PARTICIPANTS',
  APPROVE: 'Group.APPROVE',
  LIST: 'Group.LIST',
  CAN_ADD: 'Group.CAN_ADD',
  CAN_DEMOTE: 'Group.CAN_DEMOTE',
  CAN_PROMOTE: 'Group.CAN_PROMOTE',
  CAN_REMOVE: 'Group.CAN_REMOVE',
  CREATE: 'Group.CREATE',
  DEMOTE_PARTICIPANTS: 'Group.DEMOTE_PARTICIPANTS',
  GET_GROUP_INFO_FROM_INVITE_CODE: 'Group.GET_GROUP_INFO_FROM_INVITE_CODE',
  GET_GROUP_SIZE_LIMIT: 'Group.GET_GROUP_SIZE_LIMIT',
  GET_INVITE_LINK: 'Group.GET_INVITE_LINK',
  GET_MEMBERSHIP_REQUESTS: 'Group.GET_MEMBERSHIP_REQUESTS',
  GET_PARTICIPANTS: 'Group.GET_PARTICIPANTS',
  IAM_ADMIN: 'Group.IAM_ADMIN',
  IAM_MEMBER: 'Group.IAM_MEMBER',
  IAM_RESTRICTED_MEMBER: 'Group.IAM_RESTRICTED_MEMBER',
  IAM_SUPER_ADMIN: 'Group.IAM_SUPER_ADMIN',
  JOIN: 'Group.JOIN',
  LEAVE: 'Group.LEAVE',
  PROMOTE_PARTICIPANTS: 'Group.PROMOTE_PARTICIPANTS',
  REJECT: 'Group.REJECT',
  REMOVE_ICON: 'Group.REMOVE_ICON',
  REMOVE_PARTICIPANTS: 'Group.REMOVE_PARTICIPANTS',
  REVOKE_INVITE_CODE: 'Group.REVOKE_INVITE_CODE',
  SET_DESCRIPTION: 'Group.SET_DESCRIPTION',
  SET_ICON: 'Group.SET_ICON',
  SET_PROPERTY: 'Group.SET_PROPERTY',
  SET_SUBJECT: 'Group.SET_SUBJECT',
}

export const Newsletter = {
  CREATE: 'Newsletter.CREATE',
  DESTROY: 'Newsletter.DESTROY',
  EDIT: 'Newsletter.EDIT',
  GET_SUBSCRIBERS: 'Newsletter.GET_SUBSCRIBERS',
  MUTE: 'Newsletter.MUTE',
}

export const Send = {
  TEXT: 'Send.TEXT',
  IMAGE: 'Send.IMAGE',
  LOCATION: 'Send.LOCATION',
  DOCUMENT: 'Send.DOCUMENT',
  FILE: 'Send.FILE',
  POLL: 'Send.POLL',
  VCARD: 'Send.VCARD',
}

export const Status = {
  GET: 'Status.GET',
  GET_MY_STATUS: 'Status.GET_MY_STATUS',
  REMOVE: 'Status.REMOVE',
  SEND_IMAGE_STATUS: 'Status.SEND_IMAGE_STATUS',
  SEND_READ_STATUS: 'Status.SEND_READ_STATUS',
  SEND_TEXT_STATUS: 'Status.SEND_TEXT_STATUS',
  SEND_VIDEO_STATUS: 'Status.SEND_VIDEO_STATUS',
  UPDATE_PARTICIPANTS: 'Status.UPDATE_PARTICIPANTS',
}

export const Profile = {
  EDIT_BUSINESS_PROFILE: 'Profile.EDIT_BUSINESS_PROFILE',
  GET_MY_PROFILE_NAME: 'Profile.GET_MY_PROFILE_NAME',
  GET_MY_PROFILE_PICTURE: 'Profile.GET_MY_PROFILE_PICTURE',
  GET_MY_STATUS: 'Profile.GET_MY_STATUS',
  IS_BUSINESS: 'Profile.IS_BUSINESS',
  REMOVE_MY_PROFILE_PICTURE: 'Profile.REMOVE_MY_PROFILE_PICTURE',
  SET_MY_PROFILE_NAME: 'Profile.SET_MY_PROFILE_NAME',
  SET_MY_PROFILE_PICTURE: 'Profile.SET_MY_PROFILE_PICTURE',
  SET_MY_STATUS: 'Profile.SET_MY_STATUS',
}

export const AI = {
  REWRITE_MESSAGE: 'AI.REWRITE_MESSAGE',
}

export const Window = {
  READY: 'Window.READY',
  ACTIVE_CHAT: 'Window.ACTIVE_CHAT',
  GO_TO_PAGE: 'Window.GO_TO_PAGE',
  CLOSE_PAGE: 'Window.CLOSE_PAGE',
  SHOW_MODAL_MAIN: 'Window.SHOW_MODAL_MAIN',
  SHOW_MODAL_PRICING: 'Window.SHOW_MODAL_PRICING',
  SHOW_MODAL_ACTIVATION: 'Window.SHOW_MODAL_ACTIVATION',
  SHOW_MODAL_UPGRADE: 'Window.SHOW_MODAL_UPGRADE',
  SHOW_MODAL_PROFILE: 'Window.SHOW_MODAL_PROFILE',
  SHOW_MODAL_FAQ: 'Window.SHOW_MODAL_FAQ',
  SEND_BROADCAST: 'Window.SEND_BROADCAST',
}
