// src/constants/index.ts
export * as Action from './action'
export * as Setting from './setting'

export const PRIMARY_ICON = 'tabler:message-2-down'

export const Status = {
  SUCCESS: 'SUCCESS',
  IDLE: 'IDLE',
  PENDING: 'PENDING',
  FAILED: 'FAILED',
  RUNNING: 'RUNNING',
  SCHEDULER: 'SCHEDULER',
  CANCELLED: 'CANCELLED',
  PAUSED: 'PAUSED',
  DRAFT: 'DRAFT',
  POSTED: 'POSTED',
}

export const Page = {
  HOME: 'Page.HOME',
  BROADCAST: 'Page.BROADCAST',
  TOOLS: 'Page.TOOLS',
  NUMBER_VALIDATOR: 'Page.NUMBER_VALIDATOR',
  DIRECT_CHAT: 'Page.DIRECT_CHAT',
  PRIVACY: 'Page.PRIVACY',
  EXPORT: 'Page.EXPORT',
  FAQ: 'Page.FAQ',
  UPGRADE: 'Page.UPGRADE',
  ACTIVATE: 'Page.ACTIVATE',
  PROFILE: 'Page.PROFILE',
  QUICK_REPLY: 'Page.QUICK_REPLY',
  WA_ME_GENERATOR: 'Page.WA_ME_GENERATOR',
  LABEL: 'Page.LABEL',
  GROUP_LINK_GENERATOR: 'Page.GROUP_LINK_GENERATOR',
  CHAT_BACKUP: 'Page.CHAT_BACKUP', // ++ ADDED
}

export const Account = {
  BUSINESS: 'BUSINESS',
  PERSONAL: 'PERSONAL',
}

export const Message = {
  TEXT: 'TEXT',
  MEDIA: 'MEDIA',
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  AUDIO: 'AUDIO',
  FILE: 'FILE',
  LOCATION: 'LOCATION',
  VCARD: 'VCARD',
  BUTTON: 'BUTTON',
  LIST: 'LIST',
  POLL: 'POLL',
}

export const Media = {
  BROADCAST: 'BROADCAST',
  BROADCAST_TEMPLATE: 'BROADCAST_TEMPLATE',
  STATUS_CONTENT: 'STATUS_CONTENT',
  QUICK_REPLY: 'QUICK_REPLY',
}

export const ContactType = {
  ALL: 'CONTACT_TYPE_ALL',
  SAVED_CONTACTS: 'CONTACT_TYPE_SAVED_CONTACTS',
  UNSAVED_CONTACTS: 'CONTACT_TYPE_UNSAVED_CONTACTS',
}

export const AccountType = {
  ALL: 'ACCOUNT_TYPE_ALL',
  PERSONAL: 'ACCOUNT_TYPE_PERSONAL',
  BUSINESS: 'ACCOUNT_TYPE_BUSINESS',
}

export const MessageType = {
  ALL: 'MESSAGE_TYPE_ALL',
  HAVE_UNREAD_MESSAGES: 'MESSAGE_TYPE_HAVE_UNREAD_MESSAGES',
  NO_UNREAD_MESSAGES: 'MESSAGE_TYPE_NO_UNREAD_MESSAGES',
}

export const SaveAs = {
  CSV: 'SAVE_AS_CSV',
  EXCEL: 'SAVE_AS_EXCEL',
  PDF: 'SAVE_AS_PDF',
  JSON: 'SAVE_AS_JSON',
  MARKDOWN: 'SAVE_AS_MARKDOWN',
  HTML: 'SAVE_AS_HTML',
  VCARD: 'SAVE_AS_VCARD',
}
