// src/constants/setting.ts
export const LICENSE_KEY = 'SETTING_LICENSE_KEY'
export const LICENSE_INSTANCE_ID = 'SETTING_LICENSE_INSTANCE_ID'
export const LICENSE_DATA_CACHE = 'SETTING_LICENSE_DATA_CACHE'
export const IS_FIRST_TIME = 'SETTING_IS_FIRST_TIME'
export const NEED_TO_OPEN = 'SETTING_NEED_TO_OPEN'
export const HAS_ACKNOWLEDGED_BROADCAST_WARNING =
  'SETTING.HAS_ACKNOWLEDGED_BROADCAST_WARNING'
export const BLUR_PROFILE_PICTURES = 'SETTING.BLUR_PROFILE_PICTURES'
export const BLUR_MESSAGES = 'SETTING.BLUR_MESSAGES'
export const BLUR_USER_GROUP_NAMES = 'SETTING.BLUR_USER_GROUP_NAMES'
export const BLUR_RECENT_MESSAGES = 'SETTING.BLUR_RECENT_MESSAGES'
export const EXPORT_COLUMNS = 'SETTING_EXPORT_COLUMNS'
// MODIFIED: Removed SIGNATURE_ENABLED and SIGNATURE_TEXT
export const SPINTAX_TIP_DISMISSED = 'SETTING.SPINTAX_TIP_DISMISSED'
