const countries = {
  AD: { label: '🇦🇩 Andorra', phone: '376' },
  AE: { label: '🇦🇪 United Arab Emirates', phone: '971' },
  AF: { label: '🇦🇫 Afghanistan', phone: '93' },
  AG: { label: '🇦🇬 Antigua and Barbuda', phone: '1-268' },
  AI: { label: '🇦🇮 Anguilla', phone: '1-264' },
  AL: { label: '🇦🇱 Albania', phone: '355' },
  AM: { label: '🇦🇲 Armenia', phone: '374' },
  AO: { label: '🇦🇴 Angola', phone: '244' },
  AQ: { label: '🇦🇶 Antarctica', phone: '672' },
  AR: { label: '🇦🇷 Argentina', phone: '54' },
  AS: { label: '🇦🇸 American Samoa', phone: '1-684' },
  AT: { label: '🇦🇹 Austria', phone: '43' },
  AU: { label: '🇦🇺 Australia', phone: '61' },
  AW: { label: '🇦🇼 Aruba', phone: '297' },
  AX: { label: '🇦🇽 Alland Islands', phone: '358' },
  AZ: { label: '🇦🇿 Azerbaijan', phone: '994' },
  BA: { label: '🇧🇦 Bosnia and Herzegovina', phone: '387' },
  BB: { label: '🇧🇧 Barbados', phone: '1-246' },
  BD: { label: '🇧🇩 Bangladesh', phone: '880' },
  BE: { label: '🇧🇪 Belgium', phone: '32' },
  BF: { label: '🇧🇫 Burkina Faso', phone: '226' },
  BG: { label: '🇧🇬 Bulgaria', phone: '359' },
  BH: { label: '🇧🇭 Bahrain', phone: '973' },
  BI: { label: '🇧🇮 Burundi', phone: '257' },
  BJ: { label: '🇧🇯 Benin', phone: '229' },
  BL: { label: '🇧🇱 Saint Barthelemy', phone: '590' },
  BM: { label: '🇧🇲 Bermuda', phone: '1-441' },
  BN: { label: '🇧🇳 Brunei Darussalam', phone: '673' },
  BO: { label: '🇧🇴 Bolivia', phone: '591' },
  BR: { label: '🇧🇷 Brazil', phone: '55' },
  BS: { label: '🇧🇸 Bahamas', phone: '1-242' },
  BT: { label: '🇧🇹 Bhutan', phone: '975' },
  BV: { label: '🇧🇻 Bouvet Island', phone: '47' },
  BW: { label: '🇧🇼 Botswana', phone: '267' },
  BY: { label: '🇧🇾 Belarus', phone: '375' },
  BZ: { label: '🇧🇿 Belize', phone: '501' },
  CA: { label: '🇨🇦 Canada', phone: '1' },
  CC: { label: '🇨🇨 Cocos (Keeling) Islands', phone: '61' },
  CD: { label: '🇨🇩 Congo, Democratic Republic of the', phone: '243' },
  CF: { label: '🇨🇫 Central African Republic', phone: '236' },
  CG: { label: '🇨🇬 Congo, Republic of the', phone: '242' },
  CH: { label: '🇨🇭 Switzerland', phone: '41' },
  CI: { label: "🇨🇮 Cote d'Ivoire", phone: '225' },
  CK: { label: '🇨🇰 Cook Islands', phone: '682' },
  CL: { label: '🇨🇱 Chile', phone: '56' },
  CM: { label: '🇨🇲 Cameroon', phone: '237' },
  CN: { label: '🇨🇳 China', phone: '86' },
  CO: { label: '🇨🇴 Colombia', phone: '57' },
  CR: { label: '🇨🇷 Costa Rica', phone: '506' },
  CU: { label: '🇨🇺 Cuba', phone: '53' },
  CV: { label: '🇨🇻 Cape Verde', phone: '238' },
  CW: { label: '🇨🇼 Curacao', phone: '599' },
  CX: { label: '🇨🇽 Christmas Island', phone: '61' },
  CY: { label: '🇨🇾 Cyprus', phone: '357' },
  CZ: { label: '🇨🇿 Czech Republic', phone: '420' },
  DE: { label: '🇩🇪 Germany', phone: '49' },
  DJ: { label: '🇩🇯 Djibouti', phone: '253' },
  DK: { label: '🇩🇰 Denmark', phone: '45' },
  DM: { label: '🇩🇲 Dominica', phone: '1-767' },
  DO: { label: '🇩🇴 Dominican Republic', phone: '1-809' },
  DZ: { label: '🇩🇿 Algeria', phone: '213' },
  EC: { label: '🇪🇨 Ecuador', phone: '593' },
  EE: { label: '🇪🇪 Estonia', phone: '372' },
  EG: { label: '🇪🇬 Egypt', phone: '20' },
  EH: { label: '🇪🇭 Western Sahara', phone: '212' },
  ER: { label: '🇪🇷 Eritrea', phone: '291' },
  ES: { label: '🇪🇸 Spain', phone: '34' },
  ET: { label: '🇪🇹 Ethiopia', phone: '251' },
  FI: { label: '🇫🇮 Finland', phone: '358' },
  FJ: { label: '🇫🇯 Fiji', phone: '679' },
  FK: { label: '🇫🇰 Falkland Islands (Malvinas)', phone: '500' },
  FM: { label: '🇫🇲 Micronesia, Federated States of', phone: '691' },
  FO: { label: '🇫🇴 Faroe Islands', phone: '298' },
  FR: { label: '🇫🇷 France', phone: '33' },
  GA: { label: '🇬🇦 Gabon', phone: '241' },
  GB: { label: '🇬🇧 United Kingdom', phone: '44' },
  GD: { label: '🇬🇩 Grenada', phone: '1-473' },
  GE: { label: '🇬🇪 Georgia', phone: '995' },
  GF: { label: '🇬🇫 French Guiana', phone: '594' },
  GG: { label: '🇬🇬 Guernsey', phone: '44' },
  GH: { label: '🇬🇭 Ghana', phone: '233' },
  GI: { label: '🇬🇮 Gibraltar', phone: '350' },
  GL: { label: '🇬🇱 Greenland', phone: '299' },
  GM: { label: '🇬🇲 Gambia', phone: '220' },
  GN: { label: '🇬🇳 Guinea', phone: '224' },
  GP: { label: '🇬🇵 Guadeloupe', phone: '590' },
  GQ: { label: '🇬🇶 Equatorial Guinea', phone: '240' },
  GR: { label: '🇬🇷 Greece', phone: '30' },
  GS: {
    label: '🇬🇸 South Georgia and the South Sandwich Islands',
    phone: '500',
  },
  GT: { label: '🇬🇹 Guatemala', phone: '502' },
  GU: { label: '🇬🇺 Guam', phone: '1-671' },
  GW: { label: '🇬🇼 Guinea-Bissau', phone: '245' },
  GY: { label: '🇬🇾 Guyana', phone: '592' },
  HK: { label: '🇭🇰 Hong Kong', phone: '852' },
  HM: { label: '🇭🇲 Heard Island and McDonald Islands', phone: '672' },
  HN: { label: '🇭🇳 Honduras', phone: '504' },
  HR: { label: '🇭🇷 Croatia', phone: '385' },
  HT: { label: '🇭🇹 Haiti', phone: '509' },
  HU: { label: '🇭🇺 Hungary', phone: '36' },
  ID: { label: '🇮🇩 Indonesia', phone: '62' },
  IE: { label: '🇮🇪 Ireland', phone: '353' },
  IL: { label: '🇮🇱 Israel', phone: '972' },
  IM: { label: '🇮🇲 Isle of Man', phone: '44' },
  IN: { label: '🇮🇳 India', phone: '91' },
  IO: { label: '🇮🇴 British Indian Ocean Territory', phone: '246' },
  IQ: { label: '🇮🇶 Iraq', phone: '964' },
  IR: { label: '🇮🇷 Iran, Islamic Republic of', phone: '98' },
  IS: { label: '🇮🇸 Iceland', phone: '354' },
  IT: { label: '🇮🇹 Italy', phone: '39' },
  JE: { label: '🇯🇪 Jersey', phone: '44' },
  JM: { label: '🇯🇲 Jamaica', phone: '1-876' },
  JO: { label: '🇯🇴 Jordan', phone: '962' },
  JP: { label: '🇯🇵 Japan', phone: '81' },
  KE: { label: '🇰🇪 Kenya', phone: '254' },
  KG: { label: '🇰🇬 Kyrgyzstan', phone: '996' },
  KH: { label: '🇰🇭 Cambodia', phone: '855' },
  KI: { label: '🇰🇮 Kiribati', phone: '686' },
  KM: { label: '🇰🇲 Comoros', phone: '269' },
  KN: { label: '🇰🇳 Saint Kitts and Nevis', phone: '1-869' },
  KP: { label: "🇰🇵 Korea, Democratic People's Republic of", phone: '850' },
  KR: { label: '🇰🇷 Korea, Republic of', phone: '82' },
  KW: { label: '🇰🇼 Kuwait', phone: '965' },
  KY: { label: '🇰🇾 Cayman Islands', phone: '1-345' },
  KZ: { label: '🇰🇿 Kazakhstan', phone: '7' },
  LA: { label: "🇱🇦 Lao People's Democratic Republic", phone: '856' },
  LB: { label: '🇱🇧 Lebanon', phone: '961' },
  LC: { label: '🇱🇨 Saint Lucia', phone: '1-758' },
  LI: { label: '🇱🇮 Liechtenstein', phone: '423' },
  LK: { label: '🇱🇰 Sri Lanka', phone: '94' },
  LR: { label: '🇱🇷 Liberia', phone: '231' },
  LS: { label: '🇱🇸 Lesotho', phone: '266' },
  LT: { label: '🇱🇹 Lithuania', phone: '370' },
  LU: { label: '🇱🇺 Luxembourg', phone: '352' },
  LV: { label: '🇱🇻 Latvia', phone: '371' },
  LY: { label: '🇱🇾 Libya', phone: '218' },
  MA: { label: '🇲🇦 Morocco', phone: '212' },
  MC: { label: '🇲🇨 Monaco', phone: '377' },
  MD: { label: '🇲🇩 Moldova, Republic of', phone: '373' },
  ME: { label: '🇲🇪 Montenegro', phone: '382' },
  MF: { label: '🇲🇫 Saint Martin (French part)', phone: '590' },
  MG: { label: '🇲🇬 Madagascar', phone: '261' },
  MH: { label: '🇲🇭 Marshall Islands', phone: '692' },
  MK: { label: '🇲🇰 Macedonia, the Former Yugoslav Republic of', phone: '389' },
  ML: { label: '🇲🇱 Mali', phone: '223' },
  MM: { label: '🇲🇲 Myanmar', phone: '95' },
  MN: { label: '🇲🇳 Mongolia', phone: '976' },
  MO: { label: '🇲🇴 Macao', phone: '853' },
  MP: { label: '🇲🇵 Northern Mariana Islands', phone: '1-670' },
  MQ: { label: '🇲🇶 Martinique', phone: '596' },
  MR: { label: '🇲🇷 Mauritania', phone: '222' },
  MS: { label: '🇲🇸 Montserrat', phone: '1-664' },
  MT: { label: '🇲🇹 Malta', phone: '356' },
  MU: { label: '🇲🇺 Mauritius', phone: '230' },
  MV: { label: '🇲🇻 Maldives', phone: '960' },
  MW: { label: '🇲🇼 Malawi', phone: '265' },
  MX: { label: '🇲🇽 Mexico', phone: '52' },
  MY: { label: '🇲🇾 Malaysia', phone: '60' },
  MZ: { label: '🇲🇿 Mozambique', phone: '258' },
  NA: { label: '🇳🇦 Namibia', phone: '264' },
  NC: { label: '🇳🇨 New Caledonia', phone: '687' },
  NE: { label: '🇳🇪 Niger', phone: '227' },
  NF: { label: '🇳🇫 Norfolk Island', phone: '672' },
  NG: { label: '🇳🇬 Nigeria', phone: '234' },
  NI: { label: '🇳🇮 Nicaragua', phone: '505' },
  NL: { label: '🇳🇱 Netherlands', phone: '31' },
  NO: { label: '🇳🇴 Norway', phone: '47' },
  NP: { label: '🇳🇵 Nepal', phone: '977' },
  NR: { label: '🇳🇷 Nauru', phone: '674' },
  NU: { label: '🇳🇺 Niue', phone: '683' },
  NZ: { label: '🇳🇿 New Zealand', phone: '64' },
  OM: { label: '🇴🇲 Oman', phone: '968' },
  PA: { label: '🇵🇦 Panama', phone: '507' },
  PE: { label: '🇵🇪 Peru', phone: '51' },
  PF: { label: '🇵🇫 French Polynesia', phone: '689' },
  PG: { label: '🇵🇬 Papua New Guinea', phone: '675' },
  PH: { label: '🇵🇭 Philippines', phone: '63' },
  PK: { label: '🇵🇰 Pakistan', phone: '92' },
  PL: { label: '🇵🇱 Poland', phone: '48' },
  PM: { label: '🇵🇲 Saint Pierre and Miquelon', phone: '508' },
  PN: { label: '🇵🇳 Pitcairn', phone: '870' },
  PR: { label: '🇵🇷 Puerto Rico', phone: '1' },
  PS: { label: '🇵🇸 Palestine, State of', phone: '970' },
  PT: { label: '🇵🇹 Portugal', phone: '351' },
  PW: { label: '🇵🇼 Palau', phone: '680' },
  PY: { label: '🇵🇾 Paraguay', phone: '595' },
  QA: { label: '🇶🇦 Qatar', phone: '974' },
  RE: { label: '🇷🇪 Reunion', phone: '262' },
  RO: { label: '🇷🇴 Romania', phone: '40' },
  RS: { label: '🇷🇸 Serbia', phone: '381' },
  RU: { label: '🇷🇺 Russian Federation', phone: '7' },
  RW: { label: '🇷🇼 Rwanda', phone: '250' },
  SA: { label: '🇸🇦 Saudi Arabia', phone: '966' },
  SB: { label: '🇸🇧 Solomon Islands', phone: '677' },
  SC: { label: '🇸🇨 Seychelles', phone: '248' },
  SD: { label: '🇸🇩 Sudan', phone: '249' },
  SE: { label: '🇸🇪 Sweden', phone: '46' },
  SG: { label: '🇸🇬 Singapore', phone: '65' },
  SH: { label: '🇸🇭 Saint Helena', phone: '290' },
  SI: { label: '🇸🇮 Slovenia', phone: '386' },
  SJ: { label: '🇸🇯 Svalbard and Jan Mayen', phone: '47' },
  SK: { label: '🇸🇰 Slovakia', phone: '421' },
  SL: { label: '🇸🇱 Sierra Leone', phone: '232' },
  SM: { label: '🇸🇲 San Marino', phone: '378' },
  SN: { label: '🇸🇳 Senegal', phone: '221' },
  SO: { label: '🇸🇴 Somalia', phone: '252' },
  SR: { label: '🇸🇷 Suriname', phone: '597' },
  SS: { label: '🇸🇸 South Sudan', phone: '211' },
  ST: { label: '🇸🇹 Sao Tome and Principe', phone: '239' },
  SV: { label: '🇸🇻 El Salvador', phone: '503' },
  SX: { label: '🇸🇽 Sint Maarten (Dutch part)', phone: '1-721' },
  SY: { label: '🇸🇾 Syrian Arab Republic', phone: '963' },
  SZ: { label: '🇸🇿 Swaziland', phone: '268' },
  TC: { label: '🇹🇨 Turks and Caicos Islands', phone: '1-649' },
  TD: { label: '🇹🇩 Chad', phone: '235' },
  TF: { label: '🇹🇫 French Southern Territories', phone: '262' },
  TG: { label: '🇹🇬 Togo', phone: '228' },
  TH: { label: '🇹🇭 Thailand', phone: '66' },
  TJ: { label: '🇹🇯 Tajikistan', phone: '992' },
  TK: { label: '🇹🇰 Tokelau', phone: '690' },
  TL: { label: '🇹🇱 Timor-Leste', phone: '670' },
  TM: { label: '🇹🇲 Turkmenistan', phone: '993' },
  TN: { label: '🇹🇳 Tunisia', phone: '216' },
  TO: { label: '🇹🇴 Tonga', phone: '676' },
  TR: { label: '🇹🇷 Turkey', phone: '90' },
  TT: { label: '🇹🇹 Trinidad and Tobago', phone: '1-868' },
  TV: { label: '🇹🇻 Tuvalu', phone: '688' },
  TW: { label: '🇹🇼 Taiwan, Province of China', phone: '886' },
  TZ: { label: '🇹🇿 United Republic of Tanzania', phone: '255' },
  UA: { label: '🇺🇦 Ukraine', phone: '380' },
  UG: { label: '🇺🇬 Uganda', phone: '256' },
  US: { label: '🇺🇸 United States', phone: '1' },
  UY: { label: '🇺🇾 Uruguay', phone: '598' },
  UZ: { label: '🇺🇿 Uzbekistan', phone: '998' },
  VA: { label: '🇻🇦 Holy See (Vatican City State)', phone: '379' },
  VC: { label: '🇻🇨 Saint Vincent and the Grenadines', phone: '1-784' },
  VE: { label: '🇻🇪 Venezuela', phone: '58' },
  VG: { label: '🇻🇬 British Virgin Islands', phone: '1-284' },
  VI: { label: '🇻🇮 US Virgin Islands', phone: '1-340' },
  VN: { label: '🇻🇳 Vietnam', phone: '84' },
  VU: { label: '🇻🇺 Vanuatu', phone: '678' },
  WF: { label: '🇼🇫 Wallis and Futuna', phone: '681' },
  WS: { label: '🇼🇸 Samoa', phone: '685' },
  XK: { label: '🇽🇰 Kosovo', phone: '383' },
  YE: { label: '🇾🇪 Yemen', phone: '967' },
  YT: { label: '🇾🇹 Mayotte', phone: '262' },
  ZA: { label: '🇿🇦 South Africa', phone: '27' },
  ZM: { label: '🇿🇲 Zambia', phone: '260' },
  ZW: { label: '🇿🇼 Zimbabwe', phone: '263' },
}

const getCountryByCode = (code: string) => {
  return countries[code] ?? { label: '-', phone: '-' }
}

export default {
  getCountryByCode,
  countries,
}
